[font]
size = 8.0

[font.normal]
family = "monospace"
style = "Regular"

[window]
# Background opacity
opacity = 1.0
padding = { x = 2, y = 2 }

[colors]
# Default colors
[colors.primary]
background = "#0d0e1c"
foreground = "#ebdbb2"

# Normal colors
[colors.normal]
black   = "#1d2021"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

# Bright colors
[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[keyboard]
bindings = [
  # Copy/Paste (Alt + c/v)
  { key = "C", mods = "Alt", action = "Copy" },
  { key = "V", mods = "Alt", action = "Paste" },
  
  # Scrolling (Alt + j/k line, Alt + u/d page)
  { key = "K", mods = "Alt", action = "ScrollLineUp" },
  { key = "J", mods = "Alt", action = "ScrollLineDown" },
  { key = "U", mods = "Alt", action = "ScrollPageUp" },
  { key = "D", mods = "Alt", action = "ScrollPageDown" },

  # Font Size (Alt + +/-/0)
  { key = "Equals", mods = "Alt", action = "IncreaseFontSize" },
  { key = "Minus",  mods = "Alt", action = "DecreaseFontSize" },
  { key = "Key0",   mods = "Alt", action = "ResetFontSize" },
]